// core/execution-manager/ExecutionManager.js
// Orchestrates the complete START WORK sequence:
//   1. Load .env file
//   2. Open IDE
//   3. Open terminal at project path
//   4. Execute startup steps (sequential + background)
//   5. Open browser if URL configured
//   6. Start time tracking
// Also wraps STOP WORK: kill process + stop time tracker.

import { spawn, exec, execSync } from 'child_process';
import path   from 'path';
import fs     from 'fs';
import os     from 'os';
import { PROJECT_STATUS } from '../../shared/constants/index.js';

export class ExecutionManager {
  /**
   * @param {LogManager}   logManager
   * @param {TimeTracker}  timeTracker
   * @param {EnvManager}   envManager
   * @param {ProcessManager} processManager
   * @param {Function} onStatus  (projectId, status, pid) → push to renderer
   * @param {Function} onTick    (projectId, sessionId, liveSecs) → push to renderer
   */
  constructor(logManager, timeTracker, envManager, processManager, onStatus, onTick) {
    this.logManager     = logManager;
    this.timeTracker    = timeTracker;
    this.envManager     = envManager;
    this.processManager = processManager;
    this.onStatus       = onStatus || (() => {});
    this.onTick         = onTick   || (() => {});
    this._tickTimers    = new Map(); // projectId → setInterval
  }

  // ────────────────────────────────────────────────────────────────────────────
  // START WORK
  // ────────────────────────────────────────────────────────────────────────────

  /**
   * Full START WORK sequence.
   * @param {object} project     - full project row from DB
   * @param {string} sessionId   - UUID pre-generated by main.js
   * @returns {{ ok: boolean, sessionId: string, loadedEnvFile: string|null }}
   */
  async startWork(project, sessionId) {
    const cwd       = project.path;
    const activeEnv = project.active_env || 'dev';

    // ── 1. Load environment ─────────────────────────────────────────────────
    const { env: processEnv, loadedFile } = this.envManager.buildEnv(
      cwd,
      project.env_file || null,
      activeEnv,
    );

    // Inject PORT if project has one
    if (project.port) processEnv.PORT = String(project.port);

    // ── 2. Start log session ────────────────────────────────────────────────
    this.logManager.startSession(project.id, sessionId);
    this.logManager.write(project.id, 'info', `=== DevIgnite: Start Work ===`);
    this.logManager.write(project.id, 'info', `Project  : ${project.name}`);
    this.logManager.write(project.id, 'info', `Directory: ${cwd}`);
    this.logManager.write(project.id, 'info', `Env      : ${activeEnv}${loadedFile ? ` (${loadedFile})` : ' (no .env file)'}`);

    // ── 3. Start time tracking ──────────────────────────────────────────────
    this.timeTracker.start(project.id, sessionId, loadedFile);
    this._startTick(project.id, sessionId);

    this.onStatus(project.id, PROJECT_STATUS.STARTING, null);

    // ── 4. Open IDE ─────────────────────────────────────────────────────────
    this._openIDE(project);

    // ── 5. Open terminal ────────────────────────────────────────────────────
    if (project.open_terminal !== 0) {
      this._openTerminal(cwd);
    }

    // ── 6. Execute startup commands ─────────────────────────────────────────
    const steps = this._buildSteps(project);
    let mainChild = null;

    for (let i = 0; i < steps.length; i++) {
      const step = steps[i];
      this.logManager.write(project.id, 'info', `── Step ${i + 1}/${steps.length}: ${step.label}`);
      this.logManager.write(project.id, 'info', `   $ ${step.cmd}`);

      if (step.wait) {
        try {
          await this._runWait(step.cmd, cwd, processEnv, project.id);
          this.logManager.write(project.id, 'success', `   ✓ ${step.label} completed`);
        } catch (err) {
          this.logManager.write(project.id, 'error', `   ✗ ${step.label} failed: ${err.message}`);
          this.onStatus(project.id, PROJECT_STATUS.ERROR, null);
          this.timeTracker.markError(sessionId);
          this._stopTick(project.id);
          return { ok: false, error: err.message };
        }
      } else {
        mainChild = this._runBackground(step.cmd, cwd, processEnv, project.id, sessionId);
      }
    }

    if (mainChild) {
      this.processManager.register(project.id, mainChild, sessionId);
    } else {
      // No background process (IDE-only projects)
      this.onStatus(project.id, PROJECT_STATUS.RUNNING, null);
    }

    // ── 7. Open browser ─────────────────────────────────────────────────────
    if (project.open_browser !== 0 && project.url) {
      // Delay slightly so the server can start
      setTimeout(() => this._openBrowser(project.url, project.id), 2500);
    }

    return { ok: true, sessionId, loadedEnvFile: loadedFile };
  }

  // ────────────────────────────────────────────────────────────────────────────
  // STOP WORK
  // ────────────────────────────────────────────────────────────────────────────

  /**
   * @returns {{ ok: boolean, duration: object|null }}
   */
  stopWork(project, sessionId) {
    // Stop the process
    this.processManager.stop(project.id);

    // Stop time tracking
    const duration = this.timeTracker.stop(sessionId);
    this._stopTick(project.id);

    // End log session
    this.logManager.write(project.id, 'info',
      duration
        ? `=== Session ended. Duration: ${duration.formatted} ===`
        : `=== Session ended ===`
    );
    this.logManager.endSession(project.id);

    this.onStatus(project.id, PROJECT_STATUS.STOPPED, null);

    return { ok: true, duration };
  }

  // ────────────────────────────────────────────────────────────────────────────
  // Private — IDE / Terminal / Browser
  // ────────────────────────────────────────────────────────────────────────────

  _openIDE(project) {
    const isWin = os.platform() === 'win32';
    let cmd;

    switch (project.ide) {
      case 'VS Code':
        cmd = `code "${project.path}"`;
        break;
      case 'IntelliJ IDEA': {
        const launcher = this._findIntelliJ();
        cmd = launcher
          ? `"${launcher}" "${project.path}"`
          : `idea "${project.path}"`;
        break;
      }
      case 'WebStorm':       cmd = `webstorm "${project.path}"`; break;
      case 'PyCharm':        cmd = `pycharm64 "${project.path}"`; break;
      case 'Android Studio': cmd = `studio64 "${project.path}"`; break;
      default:               cmd = `code "${project.path}"`;
    }

    this.logManager.write(project.id, 'info', `Opening IDE: ${cmd}`);
    exec(cmd, { cwd: project.path }, (err) => {
      if (err) this.logManager.write(project.id, 'warn', `IDE launch: ${err.message}`);
    });
  }

  _openTerminal(cwd) {
    const plat = os.platform();

    if (plat === 'win32') {
      // Try Windows Terminal first, fall back to cmd
      exec(`wt.exe -d "${cwd}"`, (err) => {
        if (err) exec(`start cmd.exe /K "cd /d ${cwd}"`, { shell: true });
      });
    } else if (plat === 'darwin') {
      exec(`open -a Terminal "${cwd}"`);
    } else {
      // Linux: try common terminals
      const terminals = ['gnome-terminal', 'xterm', 'konsole', 'xfce4-terminal'];
      for (const t of terminals) {
        try { execSync(`which ${t}`, { stdio: 'ignore' }); exec(`${t} --working-directory="${cwd}"`); return; } catch {}
      }
    }
  }

  _openBrowser(url, projectId) {
    const plat = os.platform();
    let cmd;

    if (plat === 'win32')       cmd = `start "" "${url}"`;
    else if (plat === 'darwin') cmd = `open "${url}"`;
    else                        cmd = `xdg-open "${url}"`;

    this.logManager.write(projectId, 'info', `Opening browser: ${url}`);
    exec(cmd, (err) => {
      if (err) this.logManager.write(projectId, 'warn', `Browser open failed: ${err.message}`);
    });
  }

  // ────────────────────────────────────────────────────────────────────────────
  // Private — Command execution
  // ────────────────────────────────────────────────────────────────────────────

  _buildSteps(project) {
    let steps = [];
    try {
      const raw = project.startup_steps;
      if (raw && raw !== '[]' && raw !== 'null') steps = JSON.parse(raw);
    } catch {}

    if (steps.length > 0) return steps;

    const command = project.command;
    const isWin   = os.platform() === 'win32';

    // Python: auto-inject venv activation
    if (this._isPython(command)) {
      const venv = this._findVenv(project.path);
      if (venv) {
        if (isWin) {
          return [{
            label: 'Activate venv & start',
            cmd:   `"${path.join(venv, 'Scripts', 'activate.bat')}" && ${command}`,
            wait:  false,
          }];
        }
        return [
          { label: 'Activate venv', cmd: `source "${path.join(venv, 'bin', 'activate')}"`, wait: true },
          { label: 'Start server',  cmd: command, wait: false },
        ];
      }
    }

    // Spring Boot: prefer wrapper scripts
    if (this._isSpring(command)) {
      return [{ label: 'Start Spring Boot', cmd: this._fixSpring(command, project.path), wait: false }];
    }

    return [{ label: 'Start', cmd: command, wait: false }];
  }

  _runWait(command, cwd, env, projectId) {
    return new Promise((resolve, reject) => {
      const child = spawn(command, [], { cwd, env, shell: true, windowsHide: true });
      child.stdout.on('data', d => d.toString().split('\n').filter(Boolean)
        .forEach(l => this.logManager.write(projectId, 'info', '  ' + l)));
      child.stderr.on('data', d => d.toString().split('\n').filter(Boolean)
        .forEach(l => this.logManager.write(projectId, 'warn', '  ' + l)));
      child.on('close', code => code === 0 ? resolve() : reject(new Error(`exit ${code}`)));
      child.on('error', reject);
    });
  }

  _runBackground(command, cwd, env, projectId, sessionId) {
    const child = spawn(command, [], { cwd, env, shell: true, windowsHide: true });

    child.stdout.on('data', d => d.toString().split('\n').filter(Boolean)
      .forEach(l => this.logManager.write(projectId, 'info', l)));
    child.stderr.on('data', d => d.toString().split('\n').filter(Boolean)
      .forEach(l => this.logManager.write(projectId, 'warn', l)));

    child.on('spawn', () => {
      this.logManager.write(projectId, 'success', `Server started (PID ${child.pid})`);
      this.onStatus(projectId, PROJECT_STATUS.RUNNING, child.pid);
    });
    child.on('error', err => {
      this.logManager.write(projectId, 'error', `Spawn error: ${err.message}`);
      this.onStatus(projectId, PROJECT_STATUS.ERROR, null);
      this.timeTracker.markError(sessionId);
      this._stopTick(projectId);
    });
    child.on('close', code => {
      this.logManager.write(projectId, code === 0 ? 'info' : 'warn', `Process exited (code ${code})`);
      if (this.processManager.isRunning(projectId)) {
        // Unexpected exit — update status
        this.onStatus(projectId, PROJECT_STATUS.STOPPED, null);
        this.timeTracker.stop(sessionId);
        this._stopTick(projectId);
        this.logManager.endSession(projectId);
      }
    });

    return child;
  }

  // ────────────────────────────────────────────────────────────────────────────
  // Private — Tick timer (live duration push)
  // ────────────────────────────────────────────────────────────────────────────

  _startTick(projectId, sessionId) {
    this._stopTick(projectId);
    const timer = setInterval(() => {
      const secs = this.timeTracker.getLiveDuration(sessionId);
      this.onTick(projectId, sessionId, secs);
    }, 1000);
    this._tickTimers.set(projectId, timer);
  }

  _stopTick(projectId) {
    const t = this._tickTimers.get(projectId);
    if (t) { clearInterval(t); this._tickTimers.delete(projectId); }
  }

  stopAllTicks() {
    for (const id of this._tickTimers.keys()) this._stopTick(id);
  }

  // ────────────────────────────────────────────────────────────────────────────
  // Private — Helpers
  // ────────────────────────────────────────────────────────────────────────────

  _findIntelliJ() {
    try {
      const w = execSync('where idea64.exe', { stdio: 'pipe' }).toString().trim().split('\n')[0];
      if (w && fs.existsSync(w.trim())) return w.trim();
    } catch {}
    const bases = [
      'C:\\Program Files\\JetBrains',
      'C:\\Program Files (x86)\\JetBrains',
    ];
    for (const base of bases) {
      if (!fs.existsSync(base)) continue;
      for (const dir of fs.readdirSync(base).filter(d => d.startsWith('IntelliJ'))) {
        const exe = path.join(base, dir, 'bin', 'idea64.exe');
        if (fs.existsSync(exe)) return exe;
      }
    }
    return null;
  }

  _findVenv(projectPath) {
    for (const name of ['venv', '.venv', 'env']) {
      const candidate = path.join(projectPath, name);
      if (fs.existsSync(path.join(candidate, 'Scripts', 'python.exe')) ||
          fs.existsSync(path.join(candidate, 'bin', 'python'))) return candidate;
    }
    return null;
  }

  _isPython(cmd) { return /^python|^uvicorn|^flask|^gunicorn/.test(cmd || ''); }
  _isSpring(cmd) { return /mvn|gradle|mvnw|gradlew/.test(cmd || ''); }

  _fixSpring(command, projectPath) {
    const isWin = os.platform() === 'win32';
    if (fs.existsSync(path.join(projectPath, 'mvnw'))) {
      return command
        .replace(/^mvn(\\.exe)?\\s+/, (isWin ? '.\\mvnw.cmd' : './mvnw') + ' ')
        .replace('springboot:run', 'spring-boot:run');
    }
    if (fs.existsSync(path.join(projectPath, 'gradlew'))) {
      return command.replace(/^gradle(\\.exe)?\\s+/, (isWin ? '.\\gradlew.bat' : './gradlew') + ' ');
    }
    return command.replace('springboot:run', 'spring-boot:run');
  }
}
