// src/renderer.jsx
// React entry point — loaded by index.html via Vite.
// This replaces the default renderer.js generated by Forge.

import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App';
import './styles/app.css';

ReactDOM.createRoot(document.getElementById('root')).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);
